package joselobo_lab5p2;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JF_AgregarPersonaje = new javax.swing.JFrame();
        B_SalirAgregarPersonaje = new javax.swing.JButton();
        B_AgregarPersonaje1 = new javax.swing.JButton();
        lb_Nombre = new javax.swing.JLabel();
        lb_Debilidad = new javax.swing.JLabel();
        lb_Poder = new javax.swing.JLabel();
        lb_Fuerza = new javax.swing.JLabel();
        lb_Universo = new javax.swing.JLabel();
        lb_ResistenciaMental = new javax.swing.JLabel();
        lb_ResistenciaFisica = new javax.swing.JLabel();
        lb_Vida = new javax.swing.JLabel();
        Tb_Nombre = new javax.swing.JTextField();
        Tb_Debilidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Universo = new javax.swing.JList<>();
        TbF_FuerzaMental = new javax.swing.JFormattedTextField();
        TbF_FuerzaFisica = new javax.swing.JFormattedTextField();
        TbF_ResistenciaFisica = new javax.swing.JFormattedTextField();
        TbF_ResistenciaMental = new javax.swing.JFormattedTextField();
        TbF_Vida = new javax.swing.JFormattedTextField();
        lb_TituloAgregarPersonaje = new javax.swing.JLabel();
        JF_ListarPersonajes = new javax.swing.JFrame();
        lb_Listado = new javax.swing.JLabel();
        lb_Personajes = new javax.swing.JLabel();
        Tb_TituloListar = new javax.swing.JTextField();
        B_ListadoVolver = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JT_Personajes = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        Listado_Personajes = new javax.swing.JList<>();
        JF_SimulacionPelea = new javax.swing.JFrame();
        CB_Jugador1 = new javax.swing.JComboBox<>();
        CB_Jugador2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JL_PersonajesJugador2 = new javax.swing.JList<>();
        B_Batalla = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        JL_PersonajesJugador1 = new javax.swing.JList<>();
        B_RegresarBatalla = new javax.swing.JButton();
        lb_Titulo = new javax.swing.JLabel();
        JF_Campo = new javax.swing.JFrame();
        lb_BatallaTitulo = new javax.swing.JLabel();
        lb_JugadorActivo = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TA_Pantalla = new javax.swing.JTextArea();
        B_AtaqueFisico = new javax.swing.JButton();
        B_AtaqueMental = new javax.swing.JButton();
        B_Resistencia = new javax.swing.JButton();
        lb_Menu = new javax.swing.JLabel();
        BMenu_AgregarPersonaje = new javax.swing.JButton();
        BMenu_ListarPersonajes = new javax.swing.JButton();
        BMenu_SimulacionBatalla = new javax.swing.JButton();

        JF_AgregarPersonaje.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JF_AgregarPersonaje.setTitle("AgregarPersonaje");

        B_SalirAgregarPersonaje.setText("Salir");
        B_SalirAgregarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SalirAgregarPersonajeActionPerformed(evt);
            }
        });

        B_AgregarPersonaje1.setText("AgregarPersonaje");
        B_AgregarPersonaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AgregarPersonaje1ActionPerformed(evt);
            }
        });

        lb_Nombre.setText("Nombre");

        lb_Debilidad.setText("Debilidad");

        lb_Poder.setText("Poder");

        lb_Fuerza.setText("Fuerza");

        lb_Universo.setText("Universo");

        lb_ResistenciaMental.setText("Resistencia Mental");

        lb_ResistenciaFisica.setText("Resistencia Fisica");

        lb_Vida.setText("Vida");

        JL_Universo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Midway Games", "Capcom", "Marvel", "DC" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JL_Universo);

        TbF_FuerzaMental.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        TbF_FuerzaFisica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));

        TbF_ResistenciaFisica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));

        TbF_ResistenciaMental.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));

        TbF_Vida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));

        lb_TituloAgregarPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_TituloAgregarPersonaje.setText("Agregar Personaje");

        javax.swing.GroupLayout JF_AgregarPersonajeLayout = new javax.swing.GroupLayout(JF_AgregarPersonaje.getContentPane());
        JF_AgregarPersonaje.getContentPane().setLayout(JF_AgregarPersonajeLayout);
        JF_AgregarPersonajeLayout.setHorizontalGroup(
            JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_AgregarPersonajeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JF_AgregarPersonajeLayout.createSequentialGroup()
                        .addGroup(JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TbF_Vida, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Fuerza)
                            .addComponent(TbF_ResistenciaMental, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TbF_ResistenciaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TbF_FuerzaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ResistenciaFisica)
                            .addComponent(lb_ResistenciaMental)
                            .addComponent(TbF_FuerzaMental, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Poder)
                            .addComponent(lb_Vida))
                        .addContainerGap(204, Short.MAX_VALUE))
                    .addGroup(JF_AgregarPersonajeLayout.createSequentialGroup()
                        .addComponent(lb_Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_Universo)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JF_AgregarPersonajeLayout.createSequentialGroup()
                        .addGroup(JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_TituloAgregarPersonaje)
                            .addGroup(JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_Debilidad)
                                .addComponent(Tb_Debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(JF_AgregarPersonajeLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(B_SalirAgregarPersonaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_AgregarPersonaje1)
                .addGap(135, 135, 135))
        );
        JF_AgregarPersonajeLayout.setVerticalGroup(
            JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_AgregarPersonajeLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lb_TituloAgregarPersonaje)
                .addGap(18, 18, 18)
                .addGroup(JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Nombre)
                    .addComponent(lb_Universo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JF_AgregarPersonajeLayout.createSequentialGroup()
                        .addComponent(Tb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lb_Debilidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tb_Debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lb_Poder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TbF_FuerzaMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_Fuerza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TbF_FuerzaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_ResistenciaFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TbF_ResistenciaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_ResistenciaMental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TbF_ResistenciaMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_Vida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TbF_Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(JF_AgregarPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_SalirAgregarPersonaje)
                    .addComponent(B_AgregarPersonaje1))
                .addGap(22, 22, 22))
        );

        JF_ListarPersonajes.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JF_ListarPersonajes.setTitle("Listar Personajes");

        lb_Listado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_Listado.setText("Listado de Personajes");

        lb_Personajes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Personajes.setText("Personajes");

        Tb_TituloListar.setEditable(false);

        B_ListadoVolver.setText("Volver");
        B_ListadoVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ListadoVolverActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Midway Games");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Capcom");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Marvel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DC");
        treeNode1.add(treeNode2);
        JT_Personajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JT_Personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_PersonajesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JT_Personajes);

        Listado_Personajes.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(Listado_Personajes);

        javax.swing.GroupLayout JF_ListarPersonajesLayout = new javax.swing.GroupLayout(JF_ListarPersonajes.getContentPane());
        JF_ListarPersonajes.getContentPane().setLayout(JF_ListarPersonajesLayout);
        JF_ListarPersonajesLayout.setHorizontalGroup(
            JF_ListarPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_ListarPersonajesLayout.createSequentialGroup()
                .addGroup(JF_ListarPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JF_ListarPersonajesLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lb_Listado))
                    .addGroup(JF_ListarPersonajesLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(B_ListadoVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_ListarPersonajesLayout.createSequentialGroup()
                .addGroup(JF_ListarPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JF_ListarPersonajesLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(JF_ListarPersonajesLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lb_Personajes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(Tb_TituloListar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        JF_ListarPersonajesLayout.setVerticalGroup(
            JF_ListarPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_ListarPersonajesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lb_Listado)
                .addGap(18, 18, 18)
                .addGroup(JF_ListarPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tb_TituloListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Personajes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JF_ListarPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(B_ListadoVolver)
                .addGap(18, 18, 18))
        );

        JF_SimulacionPelea.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JF_SimulacionPelea.setTitle("Elijan sus Personajes");

        CB_Jugador1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Midway Games", "Capcom", "Marvel", "DC" }));
        CB_Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Jugador1ActionPerformed(evt);
            }
        });

        CB_Jugador2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Midway Games", "Capcom", "Marvel", "DC" }));
        CB_Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Jugador2ActionPerformed(evt);
            }
        });

        JL_PersonajesJugador2.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(JL_PersonajesJugador2);

        B_Batalla.setText("Batalla");
        B_Batalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_BatallaMouseClicked(evt);
            }
        });

        JL_PersonajesJugador1.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(JL_PersonajesJugador1);

        B_RegresarBatalla.setText("Regresar");
        B_RegresarBatalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_RegresarBatallaMouseClicked(evt);
            }
        });

        lb_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_Titulo.setText("Selecionen sus personajes");

        javax.swing.GroupLayout JF_SimulacionPeleaLayout = new javax.swing.GroupLayout(JF_SimulacionPelea.getContentPane());
        JF_SimulacionPelea.getContentPane().setLayout(JF_SimulacionPeleaLayout);
        JF_SimulacionPeleaLayout.setHorizontalGroup(
            JF_SimulacionPeleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_SimulacionPeleaLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(CB_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CB_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(JF_SimulacionPeleaLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lb_Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JF_SimulacionPeleaLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(B_RegresarBatalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Batalla)
                .addGap(151, 151, 151))
            .addGroup(JF_SimulacionPeleaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        JF_SimulacionPeleaLayout.setVerticalGroup(
            JF_SimulacionPeleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_SimulacionPeleaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lb_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(JF_SimulacionPeleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JF_SimulacionPeleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(JF_SimulacionPeleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_RegresarBatalla)
                    .addComponent(B_Batalla))
                .addGap(35, 35, 35))
        );

        JF_Campo.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JF_Campo.setTitle("Campo de Batalla");

        lb_BatallaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_BatallaTitulo.setText("Batalla");

        lb_JugadorActivo.setText("Jugador 1");

        TA_Pantalla.setColumns(20);
        TA_Pantalla.setRows(5);
        jScrollPane6.setViewportView(TA_Pantalla);

        B_AtaqueFisico.setText("Ataque Fisico");
        B_AtaqueFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_AtaqueFisicoMouseClicked(evt);
            }
        });

        B_AtaqueMental.setText("Ataque Mental");
        B_AtaqueMental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_AtaqueMentalMouseClicked(evt);
            }
        });

        B_Resistencia.setText("Resistencia");
        B_Resistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_ResistenciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JF_CampoLayout = new javax.swing.GroupLayout(JF_Campo.getContentPane());
        JF_Campo.getContentPane().setLayout(JF_CampoLayout);
        JF_CampoLayout.setHorizontalGroup(
            JF_CampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_CampoLayout.createSequentialGroup()
                .addGroup(JF_CampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JF_CampoLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(lb_BatallaTitulo))
                    .addGroup(JF_CampoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JF_CampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_JugadorActivo)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(JF_CampoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(B_AtaqueFisico)
                .addGap(90, 90, 90)
                .addComponent(B_AtaqueMental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Resistencia)
                .addGap(90, 90, 90))
        );
        JF_CampoLayout.setVerticalGroup(
            JF_CampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_CampoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lb_BatallaTitulo)
                .addGap(39, 39, 39)
                .addComponent(lb_JugadorActivo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(JF_CampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_AtaqueFisico)
                    .addComponent(B_AtaqueMental)
                    .addComponent(B_Resistencia))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        lb_Menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_Menu.setText("Menu");
        lb_Menu.setToolTipText("");

        BMenu_AgregarPersonaje.setText("Agregar Personaje");
        BMenu_AgregarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMenu_AgregarPersonajeActionPerformed(evt);
            }
        });

        BMenu_ListarPersonajes.setText("Listado de Personajes");
        BMenu_ListarPersonajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMenu_ListarPersonajesMouseClicked(evt);
            }
        });

        BMenu_SimulacionBatalla.setText("Simulacion de batalla");
        BMenu_SimulacionBatalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMenu_SimulacionBatallaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BMenu_SimulacionBatalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BMenu_ListarPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BMenu_AgregarPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lb_Menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lb_Menu)
                .addGap(18, 18, 18)
                .addComponent(BMenu_AgregarPersonaje)
                .addGap(41, 41, 41)
                .addComponent(BMenu_ListarPersonajes)
                .addGap(43, 43, 43)
                .addComponent(BMenu_SimulacionBatalla)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BMenu_AgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMenu_AgregarPersonajeActionPerformed
        // TODO add your handling code here:
        JF_AgregarPersonaje.pack();
        JF_AgregarPersonaje.setLocationRelativeTo(this);
        JF_AgregarPersonaje.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BMenu_AgregarPersonajeActionPerformed

    private void B_SalirAgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SalirAgregarPersonajeActionPerformed
        // TODO add your handling code here:
        this.setLocationRelativeTo(this);
        JF_AgregarPersonaje.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_B_SalirAgregarPersonajeActionPerformed

    private void B_AgregarPersonaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AgregarPersonaje1ActionPerformed
        // TODO add your handling code here:
        try {
            if (JL_Universo.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(JF_AgregarPersonaje, "Faltan el Universo", "Error", 2);

            } else {
                Personaje P = new Personaje(Tb_Nombre.getText(), Tb_Debilidad.getText(), JL_Universo.getSelectedValue(), Integer.parseInt(TbF_FuerzaMental.getText()), Integer.parseInt(TbF_FuerzaFisica.getText()), Integer.parseInt(TbF_ResistenciaFisica.getText()), Integer.parseInt(TbF_ResistenciaMental.getText()), Integer.parseInt(TbF_Vida.getText()));

                JOptionPane.showMessageDialog(JF_AgregarPersonaje, "Se ha agregado exitosamente", "Agregado", 1);
                Tb_Nombre.setText("");
                Tb_Debilidad.setText("");
                JL_Universo.setSelectedIndex(-1);
                TbF_FuerzaMental.setText("");
                TbF_FuerzaFisica.setText("");
                TbF_ResistenciaFisica.setText("");
                TbF_ResistenciaMental.setText("");
                TbF_Vida.setText("");

                //tree
                DefaultTreeModel model = (DefaultTreeModel) JT_Personajes.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) model.getRoot();

                if (P.getUniversoPertenece().equals("DC")) {
                    DefaultMutableTreeNode b = new DefaultMutableTreeNode(P);
                    ((DefaultMutableTreeNode) raiz.getChildAt(3)).add(b);
                }
                if (P.getUniversoPertenece().equals("Midway Games")) {
                    DefaultMutableTreeNode b = new DefaultMutableTreeNode(P);
                    ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(b);
                }
                if (P.getUniversoPertenece().equals("Capcom")) {
                    DefaultMutableTreeNode b = new DefaultMutableTreeNode(P);
                    ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(b);
                }
                if (P.getUniversoPertenece().equals("Marvel")) {
                    DefaultMutableTreeNode b = new DefaultMutableTreeNode(P);
                    ((DefaultMutableTreeNode) raiz.getChildAt(2)).add(b);
                }

                model.reload();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JF_AgregarPersonaje, "Faltan casillas por llenar o hay un dato erroneo", "Error", 2);
        }
    }//GEN-LAST:event_B_AgregarPersonaje1ActionPerformed

    private void B_ListadoVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ListadoVolverActionPerformed
        // TODO add your handling code here:
        this.setLocationRelativeTo(this);
        JF_ListarPersonajes.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_B_ListadoVolverActionPerformed

    private void JT_PersonajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_PersonajesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            DefaultListModel ModelList = (DefaultListModel) Listado_Personajes.getModel();
            DefaultTreeModel model = (DefaultTreeModel) JT_Personajes.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) model.getRoot();
            ModelList.removeAllElements();
            int row = JT_Personajes.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            JT_Personajes.setSelectionRow(row);
            Object v1
                    = JT_Personajes.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Personaje) {
                personaje_seleccionado
                        = (Personaje) nodo_seleccionado.
                                getUserObject();
                ModelList.addElement("Debilidad -> " + ((Personaje) nodo_seleccionado.getUserObject()).getDebilidad());
                ModelList.addElement("Universo -> " + ((Personaje) nodo_seleccionado.getUserObject()).getUniversoPertenece());
                ModelList.addElement("Fuerza Mental -> " + ((Personaje) nodo_seleccionado.getUserObject()).getFuerzaMental());
                ModelList.addElement("Fuerza Fisica -> " + ((Personaje) nodo_seleccionado.getUserObject()).getFuerzaFisica());
                ModelList.addElement("Resistencia Fisica -> " + ((Personaje) nodo_seleccionado.getUserObject()).getResistenciaFisica());
                ModelList.addElement("Resistencia Mental -> " + ((Personaje) nodo_seleccionado.getUserObject()).getResistenciaMental());
                ModelList.addElement("Puntos de Vida -> " + ((Personaje) nodo_seleccionado.getUserObject()).getVida());
                Tb_TituloListar.setText(personaje_seleccionado.getNombre());
            } else {
                String temp = "";
                if (nodo_seleccionado.toString().equals("DC")) {
                    Tb_TituloListar.setText("DC");
                    for (int j = 0; j < raiz.getChildAt(3).getChildCount(); j++) {
                        ModelList.addElement(raiz.getChildAt(3).getChildAt(j));
                    }
                }
                if (nodo_seleccionado.toString().equals("Midway Games")) {
                    Tb_TituloListar.setText("Midway");
                    for (int j = 0; j < raiz.getChildAt(0).getChildCount(); j++) {
                        ModelList.addElement(raiz.getChildAt(0).getChildAt(j));
                    }
                }
                if (nodo_seleccionado.toString().equals("Capcom")) {
                    Tb_TituloListar.setText("Capcom");
                    for (int j = 0; j < raiz.getChildAt(1).getChildCount(); j++) {
                        ModelList.addElement(raiz.getChildAt(1).getChildAt(j));
                    }
                }
                if (nodo_seleccionado.toString().equals("Marvel")) {
                    Tb_TituloListar.setText("Marvel");
                    for (int j = 0; j < raiz.getChildAt(2).getChildCount(); j++) {
                        ModelList.addElement(raiz.getChildAt(2).getChildAt(j));
                    }
                }

            }

        }
    }//GEN-LAST:event_JT_PersonajesMouseClicked

    private void BMenu_ListarPersonajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMenu_ListarPersonajesMouseClicked
        // TODO add your handling code here:
        JF_ListarPersonajes.pack();
        JF_ListarPersonajes.setLocationRelativeTo(this);
        JF_ListarPersonajes.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BMenu_ListarPersonajesMouseClicked

    private void BMenu_SimulacionBatallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMenu_SimulacionBatallaMouseClicked
        // TODO add your handling code here:
        JF_SimulacionPelea.pack();
        JF_SimulacionPelea.setLocationRelativeTo(this);
        JF_SimulacionPelea.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BMenu_SimulacionBatallaMouseClicked

    private void B_RegresarBatallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RegresarBatallaMouseClicked
        // TODO add your handling code here:
        this.setLocationRelativeTo(this);
        JF_SimulacionPelea.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_B_RegresarBatallaMouseClicked

    private void CB_Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Jugador1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel ModelList = (DefaultListModel) JL_PersonajesJugador1.getModel();
        DefaultTreeModel model = (DefaultTreeModel) JT_Personajes.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) model.getRoot();
        ModelList.removeAllElements();
        if (CB_Jugador1.getSelectedItem().toString().equals("DC")) {
            for (int j = 0; j < raiz.getChildAt(3).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(3).getChildAt(j));
            }
        }
        if (CB_Jugador1.getSelectedItem().toString().equals("Midway Games")) {
            for (int j = 0; j < raiz.getChildAt(0).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(0).getChildAt(j));
            }
        }
        if (CB_Jugador1.getSelectedItem().toString().equals("Capcom")) {
            for (int j = 0; j < raiz.getChildAt(1).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(1).getChildAt(j));
            }
        }
        if (CB_Jugador1.getSelectedItem().toString().equals("Marvel")) {
            for (int j = 0; j < raiz.getChildAt(2).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(2).getChildAt(j));
            }
        }
    }//GEN-LAST:event_CB_Jugador1ActionPerformed

    private void CB_Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Jugador2ActionPerformed
        // TODO add your handling code here:
        DefaultListModel ModelList = (DefaultListModel) JL_PersonajesJugador2.getModel();
        DefaultTreeModel model = (DefaultTreeModel) JT_Personajes.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) model.getRoot();
        ModelList.removeAllElements();
        if (CB_Jugador2.getSelectedItem().toString().equals("DC")) {
            for (int j = 0; j < raiz.getChildAt(3).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(3).getChildAt(j));
            }
        }
        if (CB_Jugador2.getSelectedItem().toString().equals("Midway Games")) {
            for (int j = 0; j < raiz.getChildAt(0).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(0).getChildAt(j));
            }
        }
        if (CB_Jugador2.getSelectedItem().toString().equals("Capcom")) {
            for (int j = 0; j < raiz.getChildAt(1).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(1).getChildAt(j));
            }
        }
        if (CB_Jugador2.getSelectedItem().toString().equals("Marvel")) {
            for (int j = 0; j < raiz.getChildAt(2).getChildCount(); j++) {
                ModelList.addElement(raiz.getChildAt(2).getChildAt(j));
            }
        }
    }//GEN-LAST:event_CB_Jugador2ActionPerformed

    private void B_BatallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_BatallaMouseClicked
        // TODO add your handling code here:
        personaje_Jugador1 = ((Personaje) CB_Jugador1.getSelectedItem());
        personaje_Jugador2 = ((Personaje) CB_Jugador2.getSelectedItem());
        JF_Campo.pack();
        JF_Campo.setLocationRelativeTo(this);
        JF_Campo.setVisible(true);
        JF_SimulacionPelea.setVisible(false);
    }//GEN-LAST:event_B_BatallaMouseClicked

    private void B_AtaqueFisicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_AtaqueFisicoMouseClicked
        // TODO add your handling code here:
        if (lb_JugadorActivo.getText().equals("Jugador 1")) {
            personaje_Jugador2.setVida((int) (personaje_Jugador2.getVida() - (personaje_Jugador1.getFuerzaFisica() * .5)));
            lb_JugadorActivo.setText("Jugador 2");
            TA_Pantalla.setText("El Jugador 1 le ha bajado " + (personaje_Jugador1.getFuerzaFisica() * .5) + " al jugador 2 quedadole " + personaje_Jugador2.getVida());
        } else {
            personaje_Jugador1.setVida((int) (personaje_Jugador1.getVida() - (personaje_Jugador2.getFuerzaFisica() * .5)));
            lb_JugadorActivo.setText("Jugador 1");
            TA_Pantalla.setText("El Jugador 2 le ha bajado " + (personaje_Jugador2.getFuerzaFisica() * .5) + " al jugador 1 quedadole " + personaje_Jugador1.getVida());
        }
    }//GEN-LAST:event_B_AtaqueFisicoMouseClicked

    private void B_ResistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ResistenciaMouseClicked
        // TODO add your handling code here:
        if (lb_JugadorActivo.getText().equals("Jugador 1")) {
            personaje_Jugador2.setVida((int) (personaje_Jugador2.getVida() * 1.15));
            lb_JugadorActivo.setText("Jugador 2");
            TA_Pantalla.setText("El Jugador 1 se ha aplicado resistencia " + (personaje_Jugador1.getVida() * .15) + " al jugador 1 quedandole " + personaje_Jugador1.getVida());
        } else {
            personaje_Jugador1.setVida((int) (personaje_Jugador2.getVida() * 1.15));
            lb_JugadorActivo.setText("Jugador 1");
            TA_Pantalla.setText("El Jugador 2  se ha aplicado resistencia  " + (personaje_Jugador2.getVida() * .15) + " al jugador 1 quedadole " + personaje_Jugador2.getVida());
        }
    }//GEN-LAST:event_B_ResistenciaMouseClicked

    private void B_AtaqueMentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_AtaqueMentalMouseClicked
        // TODO add your handling code here:
        if (lb_JugadorActivo.getText().equals("Jugador 1")) {
            personaje_Jugador2.setVida((int) (personaje_Jugador2.getVida() - (personaje_Jugador1.getFuerzaFisica() / 3)));
            lb_JugadorActivo.setText("Jugador 2");
            TA_Pantalla.setText("El Jugador 1 le ha bajado " + (personaje_Jugador1.getFuerzaMental() / 3) + " al jugador 2 quedadole " + personaje_Jugador2.getVida());
        } else {
            personaje_Jugador1.setVida((int) (personaje_Jugador1.getVida() - (personaje_Jugador2.getFuerzaFisica() / 3)));
            lb_JugadorActivo.setText("Jugador 1");
            TA_Pantalla.setText("El Jugador 2 le ha bajado " + (personaje_Jugador2.getFuerzaFisica() / 3) + " al jugador 1 quedadole " + personaje_Jugador1.getVida());
        }
    }//GEN-LAST:event_B_AtaqueMentalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BMenu_AgregarPersonaje;
    private javax.swing.JButton BMenu_ListarPersonajes;
    private javax.swing.JButton BMenu_SimulacionBatalla;
    private javax.swing.JButton B_AgregarPersonaje1;
    private javax.swing.JButton B_AtaqueFisico;
    private javax.swing.JButton B_AtaqueMental;
    private javax.swing.JButton B_Batalla;
    private javax.swing.JButton B_ListadoVolver;
    private javax.swing.JButton B_RegresarBatalla;
    private javax.swing.JButton B_Resistencia;
    private javax.swing.JButton B_SalirAgregarPersonaje;
    private javax.swing.JComboBox<String> CB_Jugador1;
    private javax.swing.JComboBox<String> CB_Jugador2;
    private javax.swing.JFrame JF_AgregarPersonaje;
    private javax.swing.JFrame JF_Campo;
    private javax.swing.JFrame JF_ListarPersonajes;
    private javax.swing.JFrame JF_SimulacionPelea;
    private javax.swing.JList<String> JL_PersonajesJugador1;
    private javax.swing.JList<String> JL_PersonajesJugador2;
    private javax.swing.JList<String> JL_Universo;
    private javax.swing.JTree JT_Personajes;
    private javax.swing.JList<String> Listado_Personajes;
    private javax.swing.JTextArea TA_Pantalla;
    private javax.swing.JFormattedTextField TbF_FuerzaFisica;
    private javax.swing.JFormattedTextField TbF_FuerzaMental;
    private javax.swing.JFormattedTextField TbF_ResistenciaFisica;
    private javax.swing.JFormattedTextField TbF_ResistenciaMental;
    private javax.swing.JFormattedTextField TbF_Vida;
    private javax.swing.JTextField Tb_Debilidad;
    private javax.swing.JTextField Tb_Nombre;
    private javax.swing.JTextField Tb_TituloListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lb_BatallaTitulo;
    private javax.swing.JLabel lb_Debilidad;
    private javax.swing.JLabel lb_Fuerza;
    private javax.swing.JLabel lb_JugadorActivo;
    private javax.swing.JLabel lb_Listado;
    private javax.swing.JLabel lb_Menu;
    private javax.swing.JLabel lb_Nombre;
    private javax.swing.JLabel lb_Personajes;
    private javax.swing.JLabel lb_Poder;
    private javax.swing.JLabel lb_ResistenciaFisica;
    private javax.swing.JLabel lb_ResistenciaMental;
    private javax.swing.JLabel lb_Titulo;
    private javax.swing.JLabel lb_TituloAgregarPersonaje;
    private javax.swing.JLabel lb_Universo;
    private javax.swing.JLabel lb_Vida;
    // End of variables declaration//GEN-END:variables
//Mis Propias Variables
    DefaultMutableTreeNode nodo_seleccionado;
    Personaje personaje_seleccionado;
    Personaje personaje_Jugador1;
    Personaje personaje_Jugador2;
}
